# Generated by Django 4.2.4 on 2023-08-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
    ]
